import type { Landmark, LandmarkCatalogEntry } from '@mars/shared'

export const LANDMARKS: Landmark[] = [
  {
    id: 'base_station',
    type: 'base',
    x: 12, z: 12,
    radius: 5,
    tags: ['home', 'recharge_point'],
  },
  {
    id: 'repair_tool',
    type: 'tool',
    x: 28, z: 18,
    radius: 1,
    tags: ['equipment', 'near_base'],
  },
  {
    id: 'relay_tower',
    type: 'relay',
    x: 78, z: 58,
    radius: 3,
    tags: ['damaged', 'comms'],
    repairStage: 'intact',
    repairIssues: [],
  },
  {
    id: 'beacon_A',
    type: 'beacon',
    x: 152, z: 133,
    radius: 2,
    tags: ['radio_emitter'],
  },
  {
    id: 'olympus_spire',
    type: 'spire',
    x: 97, z: 178,
    radius: 4,
    tags: ['tall', 'geological_landmark'],
    photographed: false,
  },
  {
    id: 'crater_A',
    type: 'crater',
    x: 62, z: 148,
    radius: 8,
    tags: ['large', 'unstable_rim'],
  },
  {
    id: 'crater_B',
    type: 'crater',
    x: 132, z: 32,
    radius: 5,
    tags: ['moderate'],
  },
  {
    id: 'rock_01',
    type: 'rock',
    x: 32, z: 42,
    radius: 1.5,
    tags: ['angular', 'dark_surface'],
    mineral: 'unknown',
  },
  {
    id: 'rock_02',
    type: 'rock',
    x: 58, z: 28,
    radius: 1.2,
    tags: ['layered', 'flat'],
    mineral: 'unknown',
  },
  {
    id: 'rock_03',
    type: 'rock',
    x: 72, z: 82,
    radius: 2,
    tags: ['porous', 'light_colored'],
    mineral: 'unknown',
  },
  {
    id: 'rock_04',
    type: 'rock',
    x: 112, z: 48,
    radius: 1.8,
    tags: ['very_dark', 'glassy'],
    mineral: 'unknown',
  },
  {
    id: 'rock_05',
    type: 'rock',
    x: 142, z: 98,
    radius: 1.5,
    tags: ['reddish', 'fine_grained'],
    mineral: 'unknown',
  },
  {
    id: 'rock_06',
    type: 'rock',
    x: 48, z: 112,
    radius: 2.2,
    tags: ['crystalline', 'fractures'],
    mineral: 'unknown',
  },
  {
    id: 'rock_07',
    type: 'rock',
    x: 88, z: 38,
    radius: 1.0,
    tags: ['smooth', 'rounded'],
    mineral: 'unknown',
  },
  {
    id: 'rock_08',
    type: 'rock',
    x: 125, z: 68,
    radius: 1.7,
    tags: ['rough', 'vesicular'],
    mineral: 'unknown',
  },
  {
    id: 'rock_09',
    type: 'rock',
    x: 38, z: 168,
    radius: 1.3,
    tags: ['embedded', 'stained'],
    mineral: 'unknown',
  },
]

export function landmarkCatalog(): LandmarkCatalogEntry[] {
  return LANDMARKS.map(lm => ({ id: lm.id, type: lm.type, tags: lm.tags }))
}

export const MINERAL_TYPES: Record<string, 'basalt' | 'sedimentary' | 'volcanic'> = {
  rock_01: 'basalt',
  rock_02: 'sedimentary',
  rock_03: 'volcanic',
  rock_04: 'basalt',
  rock_05: 'sedimentary',
  rock_06: 'volcanic',
  rock_07: 'basalt',
  rock_08: 'volcanic',
  rock_09: 'sedimentary',
}
